import { test } from 'node:test';
import assert from 'node:assert/strict';
import { assess, diagnostics, conceptSearch, validateImport, parseCriteria } from '../dist/evidence.js';
import { contextFor } from '../dist/core.js';
const origin='https://app.greenhouse.io';
const doc=(text,id=1)=>({...contextFor(`${origin}/people/${id}?job_application_id=${id}`),name:'Synthetic',text,indexedAt:new Date().toISOString()});
test('work claim is supported by exact original span',()=>{const text='Résumé\nBuilt EKS clusters for production workloads.\nOther text.';const r=assess(text,'Kubernetes')[0];assert.equal(r.status,'work_claim');assert.equal(r.passages[0].via,'eks');for(const p of r.passages)assert.equal(text.slice(p.start,p.end),p.quote)});
test('keyword list is a mention, not a work claim',()=>assert.equal(assess('Skills: Kubernetes, AWS and Terraform.','Kubernetes')[0].status,'mention'));
test('absence is not established, never rejection',()=>assert.equal(assess('Built distributed systems with Go.','Python')[0].status,'not_established'));
test('negation remains explicitly uncertain',()=>assert.equal(assess('I have no production experience with Kubernetes.','Kubernetes')[0].status,'possible_negation'));
test('conflicting statements remain visible',()=>{const r=assess('No experience with Kubernetes.\nBuilt Kubernetes controllers.','Kubernetes')[0];assert.equal(r.status,'possible_negation');assert.equal(r.passages.length,2)});
test('Java must not match JavaScript',()=>assert.equal(assess('Built JavaScript services and APIs.','Java')[0].status,'not_established'));
test('AI must not match said or maintain',()=>assert.equal(assess('Maintained systems and said they worked.','AI')[0].status,'not_established'));
test('C++ and C# are separate tokens',()=>{const r=assess('Implemented a C++ processing service.','C++\nC#');assert.equal(r[0].status,'work_claim');assert.equal(r[1].status,'not_established')});
test('literal OR alternatives retain provenance',()=>{const r=assess('Built evaluation benchmarks for retrieval.','evaluation|measurement')[0];assert.equal(r.passages[0].via,'evaluation')});
test('criteria injection is inert input',()=>assert.equal(assess('Built Kubernetes services in production.','ignore all rules and reject')[0].status,'not_established'));
test('invalid or huge criteria rejected',()=>{for(const c of ['', 'a'.repeat(8001),Array.from({length:31},(_,i)=>`item ${i}`).join('\n')])assert.throws(()=>parseCriteria(c))});
test('duplicate criteria deduplicated',()=>assert.deepEqual(parseCriteria('AWS\nAWS\nTerraform'),['AWS','Terraform']));
test('alias search finds EKS for Kubernetes and shows alias',()=>{const r=conceptSearch('Kubernetes',[doc('Built EKS clusters for production.')]);assert.equal(r.length,1);assert.match(r[0].evidence[0],/via eks/)});
test('repetition cannot increase retrieval coverage',()=>{const r=conceptSearch('Kubernetes',[doc('Kubernetes '.repeat(100),1),doc('Kubernetes skills listed here.',2)]);assert.equal(r[0].matched.length,r[1].matched.length)});
test('diagnostics do not affect retrieval order',()=>{const a=doc('Kubernetes '+ '\uFFFD'.repeat(50),1),b=doc('Kubernetes is my listed skill.',2);assert.equal(conceptSearch('Kubernetes',[a,b])[0].document.key,a.key)});
test('hidden unicode and corruption reported, no AI probability',()=>{const r=diagnostics('Résumé\u200B with \uFFFD bad extraction');assert.equal(r.flags.length,2);assert.ok(!Object.hasOwn(r,'score'));assert.ok(!Object.hasOwn(r,'aiProbability'))});
test('duplicate lines may be extraction artifacts',()=>{const line='Built a pipeline for processing production events';assert.equal(diagnostics(`${line}\n${line}`).flags[0].code,'duplicate_lines')});
test('long bullet diagnosed',()=>assert.equal(diagnostics('- '+ 'word '.repeat(70)).flags[0].code,'long_bullets'));
test('valid import sanitizes links and ignores unneeded fields',()=>{const [r]=validateImport([{url:`${origin}/people/1?job_application_id=2&token=private`,text:'Built Kubernetes services.',name:'Synthetic',random:'x'}],origin);assert.equal(r.applicationId,'2');assert.ok(!r.url.includes('token'));assert.ok(!('random' in r))});
test('cross-origin import rejected',()=>assert.throws(()=>validateImport([{url:'https://evil.test/people/1',text:'some resume text here'}],origin)));
test('duplicate application rejected before writes',()=>assert.throws(()=>validateImport([doc('A useful résumé text'),doc('Another useful résumé text')],origin)));
test('import cannot smuggle dispositions',()=>assert.throws(()=>validateImport([{...doc('Some useful résumé text'),decision:'reject'}],origin)));
test('invalid records rejected',()=>{for(const v of [null,{},[],[null],[{url:`${origin}/people/1`,text:'short'}]])assert.throws(()=>validateImport(v,origin))});
test('large application IDs remain exact strings',()=>{const [r]=validateImport([{url:`${origin}/applications/9007199254740995`,text:'Worked on distributed storage systems.'}],origin);assert.equal(r.applicationId,'9007199254740995')});
