import{allCandidates,deleteReview,saveCandidate,saveReview,type Decision}from"./storage";import{lexicalSearch}from"./search";
const REASONS=["Insufficient relevant experience","Required skills not demonstrated","Role/scope mismatch","Location/on-site mismatch","Work-authorization answer mismatch","Seniority mismatch","Domain mismatch","Application quality / insufficient evidence","Other"];
function key(){return location.pathname.match(/(?:candidates|applications)\/(\d+)/)?.[1]??location.pathname}
function name(){for(const s of["h1","[data-testid='candidate-name']",".candidate-name"]){const t=document.querySelector(s)?.textContent?.trim();if(t)return t}}
function text(){return((document.querySelector("main")??document.body).textContent??"").replace(/\s+/g," ").trim()}
function editing(t:EventTarget|null){const e=t as HTMLElement|null;return!!e&&(e.isContentEditable||["INPUT","TEXTAREA","SELECT"].includes(e.tagName))}
function flash(m:string){const e=document.querySelector<HTMLDivElement>("#cr-status");if(!e)return;e.textContent=m;e.dataset.active="true";setTimeout(()=>e.dataset.active="false",1600)}
async function queue(decision:Decision,reason?:string){await saveReview({candidateKey:key(),candidateName:name(),decision,reason,createdAt:new Date().toISOString(),sourceUrl:location.href});flash(`${decision.toUpperCase()}${reason?": "+reason:""} queued`)}
async function index(){await saveCandidate({key:key(),name:name(),url:location.href,text:text(),indexedAt:new Date().toISOString()})}
function nav(direction:"next"|"previous"){const pats=direction==="next"?[/next/i,/right/i]:[/previous/i,/prev/i,/left/i];const els=[...document.querySelectorAll<HTMLElement>("a,button")];const target=els.find(e=>{const label=[e.textContent,e.getAttribute("aria-label"),e.getAttribute("title")].filter(Boolean).join(" ");return pats.some(p=>p.test(label))});target?.click();if(!target)flash("No "+direction+" control found")}
function mount(){if(document.querySelector("#cautious-review"))return;const bar=document.createElement("aside");bar.id="cautious-review";bar.innerHTML=`<div class="cr-title">Cautious Review</div><div class="cr-actions"><button data-cr="advance">A Advance</button><button data-cr="maybe">M Maybe</button><button data-cr="reject">R Reject</button><button data-cr="undo">U Undo</button></div><div class="cr-search"><input id="cr-search" placeholder="Local search (/)" autocomplete="off"><div id="cr-results"></div></div><div id="cr-status"></div>`;document.body.appendChild(bar);
bar.querySelector("[data-cr='advance']")?.addEventListener("click",()=>void queue("advance"));bar.querySelector("[data-cr='maybe']")?.addEventListener("click",()=>void queue("maybe"));bar.querySelector("[data-cr='reject']")?.addEventListener("click",()=>void queue("reject"));bar.querySelector("[data-cr='undo']")?.addEventListener("click",()=>void deleteReview(key()).then(()=>flash("Queued decision removed")));
const input=bar.querySelector<HTMLInputElement>("#cr-search")!;input.addEventListener("input",async()=>{const hits=lexicalSearch(input.value,await allCandidates()).slice(0,8),out=bar.querySelector<HTMLDivElement>("#cr-results")!;out.replaceChildren(...hits.map(h=>{const a=document.createElement("a");a.href=h.candidate.url;a.textContent=`${Math.round(h.score*100)}% · ${h.candidate.name??h.candidate.key}`;a.title=h.evidence[0]??"";return a}))});void index()}
document.addEventListener("keydown",e=>{if(editing(e.target))return;const k=e.key.toLowerCase();if(k==="a")void queue("advance");else if(k==="m")void queue("maybe");else if(k==="r")void queue("reject");else if(k==="u")void deleteReview(key()).then(()=>flash("Queued decision removed"));else if(k==="j")nav("next");else if(k==="k")nav("previous");else if(k==="/"){e.preventDefault();document.querySelector<HTMLInputElement>("#cr-search")?.focus()}else if(/^[1-9]$/.test(k))void queue("reject",REASONS[Number(k)-1])});
new MutationObserver(()=>{mount();void index()}).observe(document.documentElement,{childList:true,subtree:true});mount();