import {hybridSearch,clearSemanticCache} from './semantic.js';
import {Harvest,numericId,prepareItem,executeLivePlan,downloadAttachment,snapshot,type LivePlan,type LiveItem,type Action} from './harvest.js';
import {routeIdentity,resolveIdentity} from './identity.js';
import {extractDocument} from './pdf.js';
import {blockedApplication,clearReceipts,receipts,saveReceipt} from './live-store.js';
import {saveDocument,documents,clear,reviews,purgeExpired} from './storage.js';
import {assess,diagnostics,conceptSearch,ENGINE_VERSION} from './evidence.js';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const val=(id:string)=>$<HTMLInputElement>(id).value;
const status=(s:string)=>{$('status').textContent=s;};
let api:Harvest|undefined,selected:any,attachments:any[]=[],items:LiveItem[]=[],plan:LivePlan|undefined,busy=false,controller:AbortController|undefined;
let report:any;
const hash=async(text:string)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(b=>b.toString(16).padStart(2,'0')).join('');
let origin=val('origin');const source=new URL(location.href).searchParams.get('source');
if(source){try{const h=routeIdentity(source);$<HTMLSelectElement>('origin').value=h.origin;}catch(e){status(String(e));}}
function invalidate(){plan=undefined;$<HTMLButtonElement>('execute').disabled=true;$('preview-text').textContent='';$<HTMLInputElement>('reviewed').checked=false;$<HTMLInputElement>('count').value='';}
function client(){if(!api)throw Error('Connect to Harvest first');return api;}
async function run(fn:()=>Promise<void>){if(busy)return;busy=true;try{await fn();}catch(e){status(e instanceof Error?e.message:'Operation failed');}finally{busy=false;}}
function on(id:string,fn:()=>Promise<void>){$(id).addEventListener('click',e=>{if(e.isTrusted)void run(fn);});}
function options(id:string,rows:any[],label:(r:any)=>string){const el=$<HTMLSelectElement>(id);el.replaceChildren(...rows.map(r=>{const o=document.createElement('option');o.value=String(r.id);o.textContent=label(r);return o;}));}
function renderQueue(){ $('queue-list').replaceChildren(...items.map(i=>{const a=document.createElement('article');a.textContent=`${i.label} · application ${i.before.applicationId}: ${i.action} ${i.reasonLabel??i.targetLabel??''}`;return a;}));invalidate();}
async function showReceipts(){const all=await receipts();$('receipts').textContent=JSON.stringify(all,null,2);const latest=new Map<string,typeof all[number]>();for(const r of all)latest.set(r.planId+':'+r.applicationId,r);$('receipt-summary').replaceChildren(...[...latest.values()].reverse().map(r=>{const a=document.createElement('article');a.textContent=`Application ${r.applicationId} · ${r.action} · ${r.status}${r.detail?' — '+r.detail:''}`;return a;}));}
async function selectApplication(a:any){invalidate();report=undefined;$<HTMLButtonElement>('export-evidence').disabled=true;selected=undefined;$('resume').textContent='';$<HTMLTextAreaElement>('resume').value='';$('evidence').replaceChildren();
 const c=client(),fresh=await c.application(numericId(a.id)),s=snapshot(fresh),candidate=(await c.list('/candidates?ids='+s.candidateId))[0];
 if(!candidate||String(candidate.id)!==s.candidateId)throw Error('Candidate identity mismatch');
 selected=fresh;$('candidate').textContent=`${candidate.first_name??''} ${candidate.last_name??''} · application ${s.applicationId} · ${fresh.jobs[0].name} · ${fresh.current_stage.name} · ${s.status}`;
 $('identity').textContent=`Verified candidate ${s.candidateId}, application ${s.applicationId}, job ${s.jobId}, stage ${s.stageId}.`;
 options('stage',await c.stages(s.jobId),r=>r.name);
 attachments=(await c.list('/attachments?application_ids='+s.applicationId+'&type=resume')).filter((r:any)=>r.type==='resume');
 options('attachments',attachments.map((r,i)=>({...r,id:i})),r=>r.filename??'Résumé');
 if(attachments.length===1){await retrieve();}else status(attachments.length?'Multiple résumés: choose the relevant attachment.':'No résumé attachment; import or paste text locally.');
}
async function indexText(text:string){if(!selected)throw Error('Select a verified application first');if(text.trim().length<10||text.length>200000)throw Error('Use 10–200,000 characters');const s=snapshot(selected);await saveDocument({key:`${origin}|application:${s.applicationId}`,origin,url:`${origin}/people/${s.candidateId}?job_application_id=${s.applicationId}`,applicationId:s.applicationId,candidateId:s.candidateId,name:$('candidate').textContent??'',text,indexedAt:new Date().toISOString()});}
async function retrieve(){if(!selected)throw Error('Select an application');const attachment=attachments[Number(val('attachments'))];if(!attachment?.url)throw Error('No selected attachment');status('Retrieving résumé from Greenhouse storage; extracting locally…');const result=await extractDocument(await downloadAttachment(attachment.url),attachment.filename??'resume.pdf');$<HTMLTextAreaElement>('resume').value=result.text;await indexText(result.text);status(`Résumé indexed locally · ${result.pages} pages · ${result.tinyText} text runs below 8pt. Formatting observations do not affect decisions.`);}
on('connect',async()=>{invalidate();api=undefined;items=[];renderQueue();selected=undefined;origin=val('origin');const c=new Harvest(val('key'),val('actor'));$<HTMLInputElement>('key').value='';const user=(await c.list('/users?ids='+numericId(val('actor'))))[0];if(!user||String(user.id)!==c.actor||user.deactivated!==false)throw Error('Choose your active Greenhouse user ID');api=c;await purgeExpired();options('jobs',await c.list('/jobs'),r=>`${r.name} (${r.id})`);options('reason',await c.list('/rejection_reasons'),r=>r.name);status(`Connected as ${user.name??c.actor}. No actions sent.`);await showReceipts();if(source){try{const a=await resolveIdentity(c,routeIdentity(source));await selectApplication(a);}catch(e){status((e as Error).message+' · Select a job below.');}}});
on('disconnect',async()=>{api=undefined;clearSemanticCache();selected=undefined;items=[];renderQueue();attachments=[];$<HTMLInputElement>('key').value='';$<HTMLTextAreaElement>('resume').value='';$('applications').replaceChildren();$('evidence').replaceChildren();$('candidate').textContent='Disconnected';status('Disconnected; token discarded from this page.');});
on('load',async()=>{const c=client();invalidate();const apps=await c.list(`/applications?job_ids=${numericId(val('jobs'))}&prospect=false&status=${val('app-status')==='rejected'?'rejected':'active'}`);const names=new Map<string,string>();const candidateIds=[...new Set(apps.map(a=>numericId(a.candidate_id)))];for(let i=0;i<candidateIds.length;i+=50){for(const candidate of await c.list('/candidates?ids='+candidateIds.slice(i,i+50).join(',')))names.set(String(candidate.id),`${candidate.first_name??''} ${candidate.last_name??''}`.trim());}const stageNames=new Map((await c.stages(numericId(val('jobs')))).map(s=>[String(s.id),s.name]));const currentStages=new Map<string,string>();const appIds=apps.map(a=>numericId(a.id));for(let i=0;i<appIds.length;i+=50){const rows=await c.list('/application_stages?application_ids='+appIds.slice(i,i+50).join(',')+'&current=true');for(const row of rows){const id=String(row.application_id);currentStages.set(id,currentStages.has(id)?'ambiguous':String(row.job_interview_stage_id));}}$('applications').replaceChildren(...apps.map(a=>{const b=document.createElement('button');b.textContent=`${names.get(String(a.candidate_id))??('Candidate '+a.candidate_id)} · ${stageNames.get(currentStages.get(String(a.id))??'')??'Stage unresolved'} · application ${a.id}`;b.onclick=e=>{if(e.isTrusted)void run(()=>selectApplication(a));};return b;}));status(`${apps.length} applications loaded. Select one to retrieve its résumé.`);});
on('local-queue',async()=>{const entries=await reviews(origin);$('applications').replaceChildren(...entries.map(r=>{const b=document.createElement('button');b.textContent=`Application ${r.applicationId} · local ${r.decision} · ${r.reason??''}`;b.onclick=e=>{if(e.isTrusted)void run(()=>selectApplication({id:r.applicationId}));};return b;}));status('Local decisions loaded for individual verification and mapping to actual Greenhouse reasons.');});
on('retrieve',retrieve);
$('file').addEventListener('change',e=>{if(!e.isTrusted)return;void run(async()=>{if(!selected)throw Error('Select an application first');const f=$<HTMLInputElement>('file').files?.[0];if(!f)return;if(f.size>20_000_000)throw Error('File exceeds 20 MB');const result=await extractDocument(new Uint8Array(await f.arrayBuffer()),f.name);$<HTMLTextAreaElement>('resume').value=result.text;await indexText(result.text);status('Local file extracted and indexed.');});});
on('index',async()=>{await indexText(val('resume'));status('Résumé text indexed locally.');});
on('analyze',async()=>{const text=val('resume');if(!selected)throw Error('Select an application first');const criteria=assess(text,val('criteria'));report={application:snapshot(selected),sourceSha256:await hash(text),engineVersion:ENGINE_VERSION,analyzedAt:new Date().toISOString(),criteria,criteriaText:val('criteria'),diagnostics:diagnostics(text)};$<HTMLButtonElement>('export-evidence').disabled=false;$('evidence').replaceChildren(...criteria.map(r=>{const a=document.createElement('article');a.textContent=`${r.criterion}: ${({work_claim:'Self-reported work claim',mention:'Mention only',not_established:'Not established in this text',possible_negation:'Possible negation or conflict — review'} as Record<string,string>)[r.status]}\n`+r.passages.map(p=>`[${p.start}–${p.end}] ${p.quote}`).join('\n');return a;}));const d=document.createElement('p');const diagnostic=diagnostics(text);d.textContent=`Separate document diagnostics: ${diagnostic.words} words, ${diagnostic.bullets} bullet lines. `+(diagnostic.flags.length?diagnostic.flags.map(f=>f.explanation).join(' '):'No configured formatting flags.');$('evidence').append(d);status('Source evidence shown. No disposition inferred.');});
on('semantic',async()=>{status('Loading bundled local model…');const hits=await hybridSearch(val('query'),await documents(origin),status);$('search-results').replaceChildren(...hits.map(h=>{const a=document.createElement('article');a.textContent=h.document.name+'\n'+h.passage.quote+'\nSource characters '+h.passage.start+'–'+h.passage.end+' · '+h.model;return a;}));status('Local hybrid retrieval complete. Similarity is not capability or a disposition.');});
on('search',async()=>{const hits=conceptSearch(val('query'),await documents(origin));$('search-results').replaceChildren(...hits.map(h=>{const a=document.createElement('article');a.textContent=h.document.name+'\n'+h.evidence.join('\n');return a;}));status('Local lexical and alias matches. Not a qualification ranking.');});
on('queue',async()=>{if(!selected)throw Error('Select an application');const action=val('action') as Action;const item=await prepareItem(client(),numericId(selected.id),action,action==='reject'?val('reason'):action==='move'?val('stage'):undefined);if(report?.application.applicationId===item.before.applicationId&&report.sourceSha256===await hash(val('resume')))item.evidence={sourceSha256:report.sourceSha256,engineVersion:report.engineVersion,criteria:report.criteriaText,analyzedAt:report.analyzedAt};items=items.filter(i=>i.before.applicationId!==item.before.applicationId);items.push(item);renderQueue();status('Decision queued for your final preview; no write sent.');});
on('reset',async()=>{items=[];renderQueue();status('Proposed actions cleared.');});
on('preview',async()=>{invalidate();if(!items.length)throw Error('Queue reviewed decisions first');const c=client();const refreshed:LiveItem[]=[];for(const i of items){const fresh=await prepareItem(c,i.before.applicationId,i.action,i.reasonId??(i.action==='move'?i.targetStageId:undefined));if(i.evidence)fresh.evidence=i.evidence;refreshed.push(fresh);}items=refreshed;plan={id:crypto.randomUUID(),actor:c.actor,createdAt:Date.now(),items:structuredClone(items)};$('preview-text').textContent=`Actor ${c.actor} · ${items.length} application(s) · expires in five minutes\n\n`+items.map(i=>`${i.label}\nApplication ${i.before.applicationId} / job ${i.before.jobId}\n${i.action.toUpperCase()} → ${i.reasonLabel??i.targetLabel??'Active status'}\n`).join('\n');$<HTMLButtonElement>('execute').disabled=false;status('Review this exact plan and confirm its count.');});
on('execute',async()=>{const current=plan;if(!current||!$<HTMLInputElement>('reviewed').checked||val('count')!==String(current.items.length))throw Error('Review the plan and type its exact count');invalidate();controller=new AbortController();try{await navigator.locks.request('cautious-review-live-write',{ifAvailable:true},async lock=>{if(!lock)throw Error('Another Live Review page is executing; wait for it to finish');await executeLivePlan(client(),current,current.items.length,saveReceipt,blockedApplication,controller!.signal);});items=[];renderQueue();await showReceipts();status('Execution finished. Check each receipt; cancelled, skipped, and unknown items were not assumed successful.');}finally{controller=undefined;}});
$('cancel').onclick=e=>{if(e.isTrusted){controller?.abort();status('Cancellation requested. Any request already sent must finish before the next action is stopped.');}};
on('export-evidence',async()=>{if(!report)throw Error('Analyze a résumé first');const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cautious-review-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
on('export',async()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(await receipts(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cautious-review-receipts.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
on('clear',async()=>{if(!window.confirm('Delete all local résumé text, queues and receipts? Export receipts first. Greenhouse is unchanged.'))return;await clear();await clearReceipts();clearSemanticCache();report=undefined;$<HTMLButtonElement>('export-evidence').disabled=true;items=[];renderQueue();await showReceipts();status('Local data cleared.');});
